server:
  port: 8084
spring:
  datasource:
#    url: jdbc:h2:file:/Users/stolbovd/log/h2/persons
    url: jdbc:h2:mem:persons
  data:
    rest:
      base-path: /rest/api
  jpa:
    show-sql: true
    hibernate:
      ddl-auto: update
#  h2:
#    console:
#      enabled: true
#      path: /h2-console
#logging:
#  level:
#    org.springframework.data.rest: DEBUG
#    org.hibernate: DEBUG

---

spring:
  profiles: test
  datasource:
    url: jdbc:h2:mem:test;DB_CLOSE_ON_EXIT=FALSE
